name: Update
on:
  push:
    branches:
      - master
      - main
  schedule:
    # every 1 hour
    - cron: '0 * * * *'
  workflow_dispatch:

permissions:
  contents: read
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: "0.7.0"
      - name: Install
        run: bun install
      - name: Update
        run: bun run index.ts
        env:
          BLUE_NOTION_ENVS: ${{ secrets.BLUE_NOTION_ENVS }}
