name: Update
on:
  schedule:
    # every 1 hour
    - cron: '0 * * * *'
  workflow_dispatch:
env:
  BLUE_NOTION_VERSION: v0.1.0

permissions:
  contents: read
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Download
        run: |
          curl https://github.com/azu/bluenotiondb/releases/download/${{env.BLUE_NOTION_VERSION}}/bluenotiondb -o bluenotiondb
          chmod +x bluenotiondb
      - name: Update
        run: ./bluenotiondb
        env:
          BLUE_NOTION_ENVS: ${{ secrets.BLUE_NOTION_ENVS }}
