name: Releases

on:
  push:
    tags:
      - '*'

jobs:

  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: "0.7.0"
      - name: Install
        run: bun install
      - name: Update
        run: bun run dist
      - uses: ncipollo/release-action@v1
        with:
          artifacts: "bluenotiondb"
